from django.contrib.auth.models import User
from django import forms
from core.forms.funciones_auxiliares.primero import *
from core.forms.funciones_auxiliares.segundo import *
from core.forms.funciones_auxiliares.tercero import *
from core.forms.funciones_auxiliares.cuarto import *
from core.forms.funciones_auxiliares.quinto import *
from core.forms.funciones_auxiliares.sexto import *
from core.forms.funciones_auxiliares.septimo import *
from core.forms.funciones_auxiliares.octavo import *
from core.forms.funciones_auxiliares.noveno import *
from core.forms.funciones_auxiliares.decimo import *
from django.core.exceptions import ValidationError

class FormularioUsuario(forms.ModelForm):

	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')
	
	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email=email).exists():
			raise ValidationError("Este correo electrónico ya está registrado.")
		return email

class DatosDiagnostico(forms.Form):

	#primera parte
	localizacion_dolor_derecho = localizacion_dolor_derecho()
	localizacion_dolor_izquierdo = localizacion_dolor_izquierdo()
	localizacion_cefalea_derecho = localizacion_cefalea_derecho()
	localizacion_cefalea_izquierdo = localizacion_cefalea_izquierdo()

	#segunda parte
	diente_referencia = diente_referencia()
	sobre_mordida_horizontal = sobre_mordida_horizontal()
	sobre_mordida_vertical = sobre_mordida_vertical()
	desviacion_linea_media = desviacion_linea_media()
	desviacion_linea_lado = desviacion_linea_lado()

	#tercera parte
	patron_apertura = patron_apertura()
	lado_apertura = lado_apertura()

	#cuarta parte
	apertura_sin_dolor = apertura_sin_dolor()
	apertura_maxima_no_asistida = apertura_maxima_no_asistida()
	apertura_Maxima_Asistida = apertura_Maxima_Asistida()
	terminada = terminada()
	temporal_dolor_derecho_1_4 = temporal_dolor_derecho_1_4()
	temporal_dolor_familiar_derecho_1_4 = temporal_dolor_familiar_derecho_1_4()
	temporal_cefalea_familiar_derecho_1_4 = temporal_cefalea_familiar_derecho_1_4()
	masetero_dolor_derecho_1_4 = masetero_dolor_derecho_1_4()
	masetero_dolor_familiar_derecho_1_4 = masetero_dolor_familiar_derecho_1_4()
	ATM_dolor_derecho_1_4 = ATM_dolor_derecho_1_4()
	ATM_dolor_familiar_derecho_1_4 = ATM_dolor_familiar_derecho_1_4()
	otros_Musc_M_dolor_derecho_1_4 = otros_Musc_M_dolor_derecho_1_4()
	otros_Musc_M_dolor_familiar_derecho_1_4 = otros_Musc_M_dolor_familiar_derecho_1_4()
	no_Masticat_dolor_derecho_1_4 = no_Masticat_dolor_derecho_1_4()
	no_Masticat_dolor_familiar_derecho_1_4 = no_Masticat_dolor_familiar_derecho_1_4()
	temporal_dolor_derecho_2_4 = temporal_dolor_derecho_2_4()
	temporal_dolor_familiar_derecho_2_4 = temporal_dolor_familiar_derecho_2_4()
	temporal_cefalea_familiar_derecho_2_4 = temporal_cefalea_familiar_derecho_2_4()
	masetero_dolor_derecho_2_4 = masetero_dolor_derecho_2_4()
	masetero_dolor_familiar_derecho_2_4 = masetero_dolor_familiar_derecho_2_4()
	ATM_dolor_derecho_2_4 = ATM_dolor_derecho_2_4()
	ATM_dolor_familiar_derecho_2_4 = ATM_dolor_familiar_derecho_2_4()
	otros_Musc_M_dolor_derecho_2_4 = otros_Musc_M_dolor_derecho_2_4()
	otros_Musc_M_dolor_familiar_derecho_2_4 = otros_Musc_M_dolor_familiar_derecho_2_4()
	no_Masticat_dolor_derecho_2_4 = no_Masticat_dolor_derecho_2_4()
	no_Masticat_dolor_familiar_derecho_2_4 = no_Masticat_dolor_familiar_derecho_2_4()
	temporal_dolor_izquierdo_1_4 = temporal_dolor_izquierdo_1_4()
	temporal_dolor_familiar_izquierdo_1_4 = temporal_dolor_familiar_izquierdo_1_4()
	temporal_cefalea_familiar_izquierdo_1_4 = temporal_cefalea_familiar_izquierdo_1_4()
	masetero_dolor_izquierdo_1_4 = masetero_dolor_izquierdo_1_4()
	masetero_dolor_familiar_izquierdo_1_4 = masetero_dolor_familiar_izquierdo_1_4()
	ATM_dolor_izquierdo_1_4 = ATM_dolor_izquierdo_1_4()
	ATM_dolor_familiar_izquierdo_1_4 = ATM_dolor_familiar_izquierdo_1_4()
	otros_Musc_M_dolor_izquierdo_1_4 = otros_Musc_M_dolor_izquierdo_1_4()
	otros_Musc_M_dolor_familiar_izquierdo_1_4 = otros_Musc_M_dolor_familiar_izquierdo_1_4()
	no_Masticat_dolor_izquierdo_1_4 = no_Masticat_dolor_izquierdo_1_4()
	no_Masticat_dolor_familiar_izquierdo_1_4 = no_Masticat_dolor_familiar_izquierdo_1_4()
	temporal_dolor_izquierdo_2_4 = temporal_dolor_izquierdo_2_4()
	temporal_dolor_familiar_izquierdo_2_4 = temporal_dolor_familiar_izquierdo_2_4()
	temporal_cefalea_familiar_izquierdo_2_4 = temporal_cefalea_familiar_izquierdo_2_4()
	masetero_dolor_izquierdo_2_4 = masetero_dolor_izquierdo_2_4()
	masetero_dolor_familiar_izquierdo_2_4 = masetero_dolor_familiar_izquierdo_2_4()
	ATM_dolor_izquierdo_2_4 = ATM_dolor_izquierdo_2_4()
	ATM_dolor_familiar_izquierdo_2_4 = ATM_dolor_familiar_izquierdo_2_4()
	otros_Musc_M_dolor_izquierdo_2_4 = otros_Musc_M_dolor_izquierdo_2_4()
	otros_Musc_M_dolor_familiar_izquierdo_2_4 = otros_Musc_M_dolor_familiar_izquierdo_2_4()
	no_Masticat_dolor_izquierdo_2_4 = no_Masticat_dolor_izquierdo_2_4()
	no_Masticat_dolor_familiar_izquierdo_2_4 = no_Masticat_dolor_familiar_izquierdo_2_4()

	#quinta parte
	lateralidad_derecha = lateralidad_derecha()
	lateralidad_izquierda = lateralidad_izquierda()
	protusion = protusion()
	temporal_dolor_derecho_1_5 = temporal_dolor_derecho_1_5()
	temporal_dolor_familiar_derecho_1_5 = temporal_dolor_familiar_derecho_1_5()
	temporal_cefalea_familiar_derecho_1_5 = temporal_cefalea_familiar_derecho_1_5()
	masetero_dolor_derecho_1_5 = masetero_dolor_derecho_1_5()
	masetero_dolor_familiar_derecho_1_5 = masetero_dolor_familiar_derecho_1_5()
	ATM_dolor_derecho_1_5 = ATM_dolor_derecho_1_5()
	ATM_dolor_familiar_derecho_1_5 = ATM_dolor_familiar_derecho_1_5()
	otros_Musc_M_dolor_derecho_1_5 = otros_Musc_M_dolor_derecho_1_5()
	otros_Musc_M_dolor_familiar_derecho_1_5 = otros_Musc_M_dolor_familiar_derecho_1_5()
	no_Masticat_dolor_derecho_1_5 = no_Masticat_dolor_derecho_1_5()
	no_Masticat_dolor_familiar_derecho_1_5 = no_Masticat_dolor_familiar_derecho_1_5()
	temporal_dolor_derecho_2_5 = temporal_dolor_derecho_2_5()
	temporal_dolor_familiar_derecho_2_5 = temporal_dolor_familiar_derecho_2_5()
	temporal_cefalea_familiar_derecho_2_5 = temporal_cefalea_familiar_derecho_2_5()
	masetero_dolor_derecho_2_5 = masetero_dolor_derecho_2_5()
	masetero_dolor_familiar_derecho_2_5 = masetero_dolor_familiar_derecho_2_5()
	ATM_dolor_derecho_2_5 = ATM_dolor_derecho_2_5()
	ATM_dolor_familiar_derecho_2_5 = ATM_dolor_familiar_derecho_2_5()
	otros_Musc_M_dolor_derecho_2_5 = otros_Musc_M_dolor_derecho_2_5()
	otros_Musc_M_dolor_familiar_derecho_2_5 = otros_Musc_M_dolor_familiar_derecho_2_5()
	no_Masticat_dolor_derecho_2_5 = no_Masticat_dolor_derecho_2_5()
	no_Masticat_dolor_familiar_derecho_2_5 = no_Masticat_dolor_familiar_derecho_2_5()
	temporal_dolor_derecho_3_5 = temporal_dolor_derecho_3_5()
	temporal_dolor_familiar_derecho_3_5 = temporal_dolor_familiar_derecho_3_5()
	temporal_cefalea_familiar_derecho_3_5 = temporal_cefalea_familiar_derecho_3_5()
	masetero_dolor_derecho_3_5 = masetero_dolor_derecho_3_5()
	masetero_dolor_familiar_derecho_3_5 = masetero_dolor_familiar_derecho_3_5()
	ATM_dolor_derecho_3_5 = ATM_dolor_derecho_3_5()
	ATM_dolor_familiar_derecho_3_5 = ATM_dolor_familiar_derecho_3_5()
	otros_Musc_M_dolor_derecho_3_5 = otros_Musc_M_dolor_derecho_3_5()
	otros_Musc_M_dolor_familiar_derecho_3_5 = otros_Musc_M_dolor_familiar_derecho_3_5()
	no_Masticat_dolor_derecho_3_5 = no_Masticat_dolor_derecho_3_5()
	no_Masticat_dolor_familiar_derecho_3_5 = no_Masticat_dolor_familiar_derecho_3_5()
	temporal_dolor_izquierdo_1_5 = temporal_dolor_izquierdo_1_5()
	temporal_dolor_familiar_izquierdo_1_5 = temporal_dolor_familiar_izquierdo_1_5()
	temporal_cefalea_familiar_izquierdo_1_5 = temporal_cefalea_familiar_izquierdo_1_5()
	masetero_dolor_izquierdo_1_5 = masetero_dolor_izquierdo_1_5()
	masetero_dolor_familiar_izquierdo_1_5 = masetero_dolor_familiar_izquierdo_1_5()
	ATM_dolor_izquierdo_1_5 = ATM_dolor_izquierdo_1_5()
	ATM_dolor_familiar_izquierdo_1_5 = ATM_dolor_familiar_izquierdo_1_5()
	otros_Musc_M_dolor_izquierdo_1_5 = otros_Musc_M_dolor_izquierdo_1_5()
	otros_Musc_M_dolor_familiar_izquierdo_1_5 = otros_Musc_M_dolor_familiar_izquierdo_1_5()
	no_Masticat_dolor_izquierdo_1_5 = no_Masticat_dolor_izquierdo_1_5()
	no_Masticat_dolor_familiar_izquierdo_1_5 = no_Masticat_dolor_familiar_izquierdo_1_5()
	temporal_dolor_izquierdo_2_5 = temporal_dolor_izquierdo_2_5()
	temporal_dolor_familiar_izquierdo_2_5 = temporal_dolor_familiar_izquierdo_2_5()
	temporal_cefalea_familiar_izquierdo_2_5 = temporal_cefalea_familiar_izquierdo_2_5()
	masetero_dolor_izquierdo_2_5 = masetero_dolor_izquierdo_2_5()
	masetero_dolor_familiar_izquierdo_2_5 = masetero_dolor_familiar_izquierdo_2_5()
	ATM_dolor_izquierdo_2_5 = ATM_dolor_izquierdo_2_5()
	ATM_dolor_familiar_izquierdo_2_5 = ATM_dolor_familiar_izquierdo_2_5()
	otros_Musc_M_dolor_izquierdo_2_5 = otros_Musc_M_dolor_izquierdo_2_5()
	otros_Musc_M_dolor_familiar_izquierdo_2_5 = otros_Musc_M_dolor_familiar_izquierdo_2_5()
	no_Masticat_dolor_izquierdo_2_5 = no_Masticat_dolor_izquierdo_2_5()
	no_Masticat_dolor_familiar_izquierdo_2_5 = no_Masticat_dolor_familiar_izquierdo_2_5()
	temporal_dolor_izquierdo_3_5 = temporal_dolor_izquierdo_3_5()
	temporal_dolor_familiar_izquierdo_3_5 = temporal_dolor_familiar_izquierdo_3_5()
	temporal_cefalea_familiar_izquierdo_3_5 = temporal_cefalea_familiar_izquierdo_3_5()
	masetero_dolor_izquierdo_3_5 = masetero_dolor_izquierdo_3_5()
	masetero_dolor_familiar_izquierdo_3_5 = masetero_dolor_familiar_izquierdo_3_5()
	ATM_dolor_izquierdo_3_5 = ATM_dolor_izquierdo_3_5()
	ATM_dolor_familiar_izquierdo_3_5 = ATM_dolor_familiar_izquierdo_3_5()
	otros_Musc_M_dolor_izquierdo_3_5 = otros_Musc_M_dolor_izquierdo_3_5()
	otros_Musc_M_dolor_familiar_izquierdo_3_5 = otros_Musc_M_dolor_familiar_izquierdo_3_5()
	no_Masticat_dolor_izquierdo_3_5 = no_Masticat_dolor_izquierdo_3_5()
	no_Masticat_dolor_familiar_izquierdo_3_5 = no_Masticat_dolor_familiar_izquierdo_3_5()

	#sexta parte
	click_apertura_derecho_6 = click_apertura_derecho_6()
	click_cierre_derecho_6 = click_cierre_derecho_6()
	click_paciente_derecho_6 = click_paciente_derecho_6()
	click_dolor_derecho_6 = click_dolor_derecho_6()
	click_dolor_familiar_derecho_6 = click_dolor_familiar_derecho_6()
	crepitacion_apertura_derecho_6 = crepitacion_apertura_derecho_6()
	crepitacion_cierre_derecho_6 = crepitacion_cierre_derecho_6()
	crepitacion_paciente_derecho_6 = crepitacion_paciente_derecho_6()
	click_apertura_izquierdo_6 = click_apertura_izquierdo_6()
	click_cierre_izquierdo_6 = click_cierre_izquierdo_6()
	click_paciente_izquierdo_6 = click_paciente_izquierdo_6()
	click_dolor_izquierdo_6 = click_dolor_izquierdo_6()
	click_dolor_familiar_izquierdo_6 = click_dolor_familiar_izquierdo_6()
	crepitacion_apertura_izquierdo_6 = crepitacion_apertura_izquierdo_6()
	crepitacion_cierre_izquierdo_6 = crepitacion_cierre_izquierdo_6()
	crepitacion_paciente_izquierdo_6 = crepitacion_paciente_izquierdo_6()

	#septima parte

	click_examinador_derecho_7 = click_examinador_derecho_7()
	click_paciente_derecho_7 = click_paciente_derecho_7()
	click_dolor_derecho_7 = click_dolor_derecho_7()
	click_dolor_familiar_derecho_7 = click_dolor_familiar_derecho_7()
	crepitacion_examinador_derecho_7 = crepitacion_examinador_derecho_7()
	crepitacion_paciente_derecho_7 = crepitacion_paciente_derecho_7()
	click_examinador_izquierdo_7 = click_examinador_izquierdo_7()
	click_paciente_izquierdo_7 = click_paciente_izquierdo_7()
	click_dolor_izquierdo_7 = click_dolor_izquierdo_7()
	click_dolor_familiar_izquierdo_7 = click_dolor_familiar_izquierdo_7()
	crepitacion_examinador_izquierdo_7 = crepitacion_examinador_izquierdo_7()
	crepitacion_paciente_izquierdo_7 = crepitacion_paciente_izquierdo_7()

	#octava parte
	mientras_abre_bloqueo_derecho_8 = mientras_abre_bloqueo_derecho_8()
	mientras_abre_paciente_derecho_8 = mientras_abre_paciente_derecho_8()
	mientras_abre_evaluador_derecho_8 = mientras_abre_evaluador_derecho_8()
	posicion_max_apertura_bloqueo_derecho_8 = posicion_max_apertura_bloqueo_derecho_8()
	posicion_max_apertura_paciente_derecho_8 = posicion_max_apertura_paciente_derecho_8()
	posicion_max_apertura_evaluador_derecho_8 = posicion_max_apertura_evaluador_derecho_8()
	mientras_abre_bloqueo_izquierdo_8 = mientras_abre_bloqueo_izquierdo_8()
	mientras_abre_paciente_izquierdo_8 = mientras_abre_paciente_izquierdo_8()
	mientras_abre_evaluador_izquierdo_8 = mientras_abre_evaluador_izquierdo_8()
	posicion_max_apertura_bloqueo_izquierdo_8 = posicion_max_apertura_bloqueo_izquierdo_8()
	posicion_max_apertura_paciente_izquierdo_8 = posicion_max_apertura_paciente_izquierdo_8()
	posicion_max_apertura_evaluador_izquierdo_8 = posicion_max_apertura_evaluador_izquierdo_8()
	

	#novena parte
	posterior_dolor_derecho_9 = posterior_dolor_derecho_9() 
	posterior_dolor_familiar_derecho_9 = posterior_dolor_familiar_derecho_9()
	posterior_cefalea_familiar_derecho_9 = posterior_cefalea_familiar_derecho_9()
	posterior_dolor_referido_derecho_9 = posterior_dolor_referido_derecho_9()
	medio_dolor_derecho_9 = medio_dolor_derecho_9()
	medio_dolor_familiar_derecho_9 = medio_dolor_familiar_derecho_9()
	medio_cefalea_familiar_derecho_9 = medio_cefalea_familiar_derecho_9()
	medio_dolor_referido_derecho_9 = medio_dolor_referido_derecho_9()
	anterior_dolor_derecho_9 = anterior_dolor_derecho_9()
	anterior_dolor_familiar_derecho_9 = anterior_dolor_familiar_derecho_9()
	anterior_cefalea_familiar_derecho_9 = anterior_cefalea_familiar_derecho_9()
	anterior_dolor_referido_derecho_9 = anterior_dolor_referido_derecho_9()
	origen_dolor_derecho_9 = origen_dolor_derecho_9()
	origen_dolor_familiar_derecho_9 = origen_dolor_familiar_derecho_9()
	origen_dolor_referido_derecho_9 = origen_dolor_referido_derecho_9()
	cuerpo_dolor_derecho_9 = cuerpo_dolor_derecho_9()
	cuerpo_dolor_familiar_derecho_9 = cuerpo_dolor_familiar_derecho_9()
	cuerpo_dolor_referido_derecho_9 = cuerpo_dolor_referido_derecho_9()
	insercion_dolor_derecho_9 = insercion_dolor_derecho_9()
	insercion_dolor_familiar_derecho_9 = insercion_dolor_familiar_derecho_9()
	insercion_dolor_referido_derecho_9 = insercion_dolor_referido_derecho_9()
	lateral_dolor_derecho_9 = lateral_dolor_derecho_9()
	lateral_dolor_familiar_derecho_9 = lateral_dolor_familiar_derecho_9()
	lateral_dolor_referido_derecho_9 = lateral_dolor_referido_derecho_9()
	alrededor_dolor_derecho_9 = alrededor_dolor_derecho_9()
	alrededor_dolor_familiar_derecho_9 = alrededor_dolor_familiar_derecho_9()
	alrededor_dolor_referido_derecho_9 = alrededor_dolor_referido_derecho_9()
	posterior_dolor_izquierdo_9 = posterior_dolor_izquierdo_9() 
	posterior_dolor_familiar_izquierdo_9 = posterior_dolor_familiar_izquierdo_9()
	posterior_cefalea_familiar_izquierdo_9 = posterior_cefalea_familiar_izquierdo_9()
	posterior_dolor_referido_izquierdo_9 = posterior_dolor_referido_izquierdo_9()
	medio_dolor_izquierdo_9 = medio_dolor_izquierdo_9()
	medio_dolor_familiar_izquierdo_9 = medio_dolor_familiar_izquierdo_9()
	medio_cefalea_familiar_izquierdo_9 = medio_cefalea_familiar_izquierdo_9()
	medio_dolor_referido_izquierdo_9 = medio_dolor_referido_izquierdo_9()
	anterior_dolor_izquierdo_9 = anterior_dolor_izquierdo_9()
	anterior_dolor_familiar_izquierdo_9 = anterior_dolor_familiar_izquierdo_9()
	anterior_cefalea_familiar_izquierdo_9 = anterior_cefalea_familiar_izquierdo_9()
	anterior_dolor_referido_izquierdo_9 = anterior_dolor_referido_izquierdo_9()
	origen_dolor_izquierdo_9 = origen_dolor_izquierdo_9()
	origen_dolor_familiar_izquierdo_9 = origen_dolor_familiar_izquierdo_9()
	origen_dolor_referido_izquierdo_9 = origen_dolor_referido_izquierdo_9()
	cuerpo_dolor_izquierdo_9 = cuerpo_dolor_izquierdo_9()
	cuerpo_dolor_familiar_izquierdo_9 = cuerpo_dolor_familiar_izquierdo_9()
	cuerpo_dolor_referido_izquierdo_9 = cuerpo_dolor_referido_izquierdo_9()
	insercion_dolor_izquierdo_9 = insercion_dolor_izquierdo_9()
	insercion_dolor_familiar_izquierdo_9 = insercion_dolor_familiar_izquierdo_9()
	insercion_dolor_referido_izquierdo_9 = insercion_dolor_referido_izquierdo_9()
	lateral_dolor_izquierdo_9 = lateral_dolor_izquierdo_9()
	lateral_dolor_familiar_izquierdo_9 = lateral_dolor_familiar_izquierdo_9()
	lateral_dolor_referido_izquierdo_9 = lateral_dolor_referido_izquierdo_9()
	alrededor_dolor_izquierdo_9 = alrededor_dolor_izquierdo_9()
	alrededor_dolor_familiar_izquierdo_9 = alrededor_dolor_familiar_izquierdo_9()
	alrededor_dolor_referido_izquierdo_9 = alrededor_dolor_referido_izquierdo_9()

	#decima parte
	mandibular_dolor_derecho_10 = mandibular_dolor_derecho_10()
	mandibular_dolor_familiar_derecho_10 = mandibular_dolor_familiar_derecho_10()
	mandibular_dolor_referido_derecho_10 = mandibular_dolor_referido_derecho_10()
	submandibular_dolor_derecho_10 = submandibular_dolor_derecho_10()
	submandibular_dolor_familiar_derecho_10 = submandibular_dolor_familiar_derecho_10()
	submandibular_dolor_referido_derecho_10 = submandibular_dolor_referido_derecho_10()
	lateral_dolor_derecho_10 = lateral_dolor_derecho_10()
	lateral_dolor_familiar_derecho_10 = lateral_dolor_familiar_derecho_10()
	lateral_dolor_referido_derecho_10 = lateral_dolor_referido_derecho_10()
	temporal_dolor_derecho_10 = temporal_dolor_derecho_10()
	temporal_dolor_familiar_derecho_10 = temporal_dolor_familiar_derecho_10()
	temporal_dolor_referido_derecho_10 = temporal_dolor_referido_derecho_10()
	mandibular_dolor_izquierdo_10 = mandibular_dolor_izquierdo_10()
	mandibular_dolor_familiar_izquierdo_10 = mandibular_dolor_familiar_izquierdo_10()
	mandibular_dolor_referido_izquierdo_10 = mandibular_dolor_referido_izquierdo_10()
	submandibular_dolor_izquierdo_10 = submandibular_dolor_izquierdo_10()
	submandibular_dolor_familiar_izquierdo_10 = submandibular_dolor_familiar_izquierdo_10()
	submandibular_dolor_referido_izquierdo_10 = submandibular_dolor_referido_izquierdo_10()
	lateral_dolor_izquierdo_10 = lateral_dolor_izquierdo_10()
	lateral_dolor_familiar_izquierdo_10 = lateral_dolor_familiar_izquierdo_10()
	lateral_dolor_referido_izquierdo_10 = lateral_dolor_referido_izquierdo_10()
	temporal_dolor_izquierdo_10 = temporal_dolor_izquierdo_10()
	temporal_dolor_familiar_izquierdo_10 = temporal_dolor_familiar_izquierdo_10()
	temporal_dolor_referido_izquierdo_10 = temporal_dolor_referido_izquierdo_10()
